this_list = ["apple", "banana","cherry","orange","kiwi","melon","mango"]
# print(this_list)
# print(this_list[1])
# print(this_list[-1])
print(this_list[2:5])
print(this_list[:5])
print(this_list[2:])
print(this_list[-4:-1])
# print(type(this_list[2:5]))
# print(type(this_list[2]))